### PR TITLE
Issue: #36

### LINKED ISSUE #36: make validation 'start' is set before 'end' in Activity
I would like to invalidate the instance of `activity` model if `start` is later than `end`.
But now, it is not as it.

- reference (written in Japanese)
https://noumenon-th.net/programming/2019/11/12/django-validation/

### PR DESCRIPTION
**Pull request by Deepanshusaxena1**

### CODE REVIEW

**Comment by siruku6** [comment]
@Deepanshusaxena1 
Thank you for your pull request!

By the way, could you enable CircleCI to recognize your forked repository?
I would like to know whether the unit tests are passed or not.

But if it seems difficult for you, I'll check it on my local environment, so please tell me in that case!

**Comment by Deepanshusaxena1** [comment]
@siruku6 
Tried integrating CircleCI, pytest was getting failed because `SOCIAL_AUTH_GOOGLE_OAUTH2_KEY` is not set.

Can you please check this on your local?

**Comment by Deepanshusaxena1** [comment]
@siruku6

I have integrated `CircleCI`, all checks have passed.

**Review by siruku6 — APPROVED** [review]

**Comment by Deepanshusaxena1** [comment]
@siruku6 Thanks for approving this PR.
When are you planning to merge these changes?

**Comment by siruku6** [comment]
> @siruku6 Thanks for approving this PR. When are you planning to merge these changes?

I'm sorry for being late!
Actually, I was confirming the behavior you created.
And I confirmed that you surely prevent data with reversed time from being registered, so I merge it!

Thank you for your great contribution!! 🤗

**Pull request merged**
